2025-03-11 21:12:10,971 INFO: Email Automation System startup [in D:\W\email_automation\app.py:27]
2025-03-11 21:12:10,973 INFO: Database tables created/verified [in D:\W\email_automation\app.py:33]
2025-03-11 21:12:10,974 INFO: Starting Email Automation Server... [in D:\W\email_automation\app.py:39]
2025-03-11 21:12:10,974 INFO: Initializing email processing scheduler... [in D:\W\email_automation\app.py:42]
2025-03-11 21:12:10,974 ERROR: Error processing email queue: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\scheduler_utils.py:213]
2025-03-11 21:16:44,517 INFO: Email Automation System startup [in D:\W\email_automation\app.py:27]
2025-03-11 21:16:44,519 INFO: Database tables created/verified [in D:\W\email_automation\app.py:33]
2025-03-11 21:16:44,520 INFO: Starting Email Automation Server... [in D:\W\email_automation\app.py:39]
2025-03-11 21:16:44,521 INFO: Initializing email processing scheduler... [in D:\W\email_automation\app.py:42]
2025-03-11 21:16:44,521 ERROR: Error processing email queue: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\scheduler_utils.py:213]
2025-03-11 21:17:05,833 INFO: Email Automation System startup [in D:\W\email_automation\app.py:27]
2025-03-11 21:17:05,835 INFO: Database tables created/verified [in D:\W\email_automation\app.py:33]
2025-03-11 21:17:05,835 INFO: Starting Email Automation Server... [in D:\W\email_automation\app.py:39]
2025-03-11 21:17:05,835 INFO: Initializing email processing scheduler... [in D:\W\email_automation\app.py:42]
2025-03-11 21:17:05,836 ERROR: Error processing email queue: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\scheduler_utils.py:213]
2025-03-11 21:26:00,085 INFO: Beakon Solutions system startup [in D:\W\email_automation\app.py:32]
2025-03-11 21:26:00,086 INFO: Starting Beakon Solutions Server... [in D:\W\email_automation\app.py:38]
2025-03-11 21:26:00,086 INFO: Initializing email processing scheduler... [in D:\W\email_automation\app.py:41]
2025-03-11 21:26:00,087 ERROR: Error processing email queue: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\scheduler_utils.py:213]
2025-03-11 21:29:13,022 INFO: Beakon Solutions system startup [in D:\W\email_automation\app.py:32]
2025-03-11 21:29:13,022 INFO: Starting Beakon Solutions Server... [in D:\W\email_automation\app.py:38]
2025-03-11 21:29:13,023 INFO: Initializing email processing scheduler... [in D:\W\email_automation\app.py:41]
2025-03-11 21:29:13,023 ERROR: Error processing email queue: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\scheduler_utils.py:213]
2025-03-11 21:31:24,339 INFO: Beakon Solutions system startup [in D:\W\email_automation\app.py:32]
2025-03-11 21:31:24,339 INFO: Starting Beakon Solutions Server... [in D:\W\email_automation\app.py:38]
2025-03-11 21:31:24,340 INFO: Initializing email processing scheduler... [in D:\W\email_automation\app.py:41]
2025-03-11 21:31:24,340 ERROR: Error processing email queue: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\scheduler_utils.py:213]
2025-03-11 21:35:16,034 INFO: Beakon Solutions system startup [in D:\W\email_automation\app.py:32]
2025-03-11 21:35:16,034 INFO: Starting Beakon Solutions Server... [in D:\W\email_automation\app.py:38]
2025-03-11 21:35:16,034 INFO: Initializing email processing scheduler... [in D:\W\email_automation\app.py:41]
2025-03-11 21:35:16,035 ERROR: Error processing email queue: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\scheduler_utils.py:213]
2025-03-11 21:38:45,436 INFO: Beakon Solutions system startup [in D:\W\email_automation\app.py:32]
2025-03-11 21:38:45,436 INFO: Starting Beakon Solutions Server... [in D:\W\email_automation\app.py:38]
2025-03-11 21:38:45,436 INFO: Initializing email processing scheduler... [in D:\W\email_automation\app.py:41]
2025-03-11 21:38:45,437 ERROR: Error processing email queue: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\scheduler_utils.py:213]
2025-03-11 21:39:06,904 ERROR: Error scheduling email batch: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\scheduler_utils.py:364]
2025-03-11 21:39:06,908 ERROR: Error scheduling email batch: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\scheduler_utils.py:364]
2025-03-11 21:39:38,338 ERROR: Error scheduling email batch: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\scheduler_utils.py:364]
2025-03-11 21:43:41,742 INFO: Beakon Solutions system startup [in D:\W\email_automation\app.py:32]
2025-03-11 21:43:41,743 INFO: Starting Beakon Solutions Server... [in D:\W\email_automation\app.py:38]
2025-03-11 21:43:41,743 INFO: Initializing email processing scheduler... [in D:\W\email_automation\app.py:41]
2025-03-11 21:44:11,805 ERROR: Error scheduling email batch: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\scheduler_utils.py:364]
2025-03-11 21:44:11,807 ERROR: Error scheduling email batch: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\scheduler_utils.py:364]
2025-03-11 21:47:09,426 INFO: Beakon Solutions system startup [in D:\W\email_automation\app.py:32]
2025-03-11 21:47:09,426 INFO: Starting Beakon Solutions Server... [in D:\W\email_automation\app.py:38]
2025-03-11 21:47:09,427 INFO: Initializing email processing scheduler... [in D:\W\email_automation\app.py:41]
2025-03-11 21:47:53,530 ERROR: Error loading dashboard: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:90]
2025-03-11 21:47:58,822 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,823 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,824 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,824 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,825 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,826 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,826 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,826 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,827 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,829 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,829 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,830 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,831 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,832 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,832 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,833 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,834 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,834 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:47:58,835 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:48:03,526 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:48:03,527 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:48:03,528 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:48:03,528 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
2025-03-11 21:48:03,529 ERROR: Error calculating sent emails: 'method_descriptor' object has no attribute 'today' [in D:\W\email_automation\app\controllers\routes.py:646]
