2025-03-11 20:47:44,946 INFO: Email Automation System startup [in D:\W\email_automation\app.py:25]
2025-03-11 20:47:44,948 INFO: Database tables created/verified [in D:\W\email_automation\app.py:30]
2025-03-11 20:48:09,028 INFO: Starting check for email replies across all accounts [in D:\W\email_automation\app\utils\scheduler_utils.py:52]
2025-03-11 20:48:09,029 ERROR: Error processing email queue: (sqlite3.OperationalError) no such column: email.campaign_id
[SQL: SELECT email.id AS email_id, email.account_id AS email_account_id, email.recipient_id AS email_recipient_id, email.template_id AS email_template_id, email.subject AS email_subject, email.body AS email_body, email.status AS email_status, email.scheduled_at AS email_scheduled_at, email.sent_at AS email_sent_at, email.response_received_at AS email_response_received_at, email.is_follow_up AS email_is_follow_up, email.parent_email_id AS email_parent_email_id, email.created_at AS email_created_at, email.updated_at AS email_updated_at, email.response_subject AS email_response_subject, email.response_content AS email_response_content, email.campaign_id AS email_campaign_id 
FROM email 
WHERE email.status = ? AND email.scheduled_at <= ? ORDER BY email.scheduled_at]
[parameters: ('PENDING', '2025-03-11 20:48:09.028844')]
(Background on this error at: https://sqlalche.me/e/14/e3q8) [in D:\W\email_automation\app\utils\scheduler_utils.py:141]
2025-03-11 20:48:09,030 INFO: Checking 19 accounts for email replies [in D:\W\email_automation\app\utils\scheduler_utils.py:59]
2025-03-11 20:48:09,032 INFO: Checking replies for account: business@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:09,032 INFO: Connecting to IMAP server imap.hostinger.com:993 for account business@beakonagency.com [in D:\W\email_automation\app\utils\email_utils.py:414]
2025-03-11 20:48:09,583 INFO: Attempting login with username: business@beakonagency.com [in D:\W\email_automation\app\utils\email_utils.py:424]
2025-03-11 20:48:09,882 INFO: Successfully logged into IMAP server for business@beakonagency.com [in D:\W\email_automation\app\utils\email_utils.py:433]
2025-03-11 20:48:10,038 INFO: Selected INBOX with 24 messages [in D:\W\email_automation\app\utils\email_utils.py:446]
2025-03-11 20:48:10,348 ERROR: Error checking for replies: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\email_utils.py:621]
2025-03-11 20:48:10,349 ERROR: Traceback (most recent call last):
  File "D:\W\email_automation\app\utils\email_utils.py", line 449, in check_for_replies
    date = (datetime.datetime.now() - datetime.timedelta(days=30)).strftime("%d-%b-%Y")
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
 [in D:\W\email_automation\app\utils\email_utils.py:622]
2025-03-11 20:48:10,350 INFO: Checking replies for account: varshith@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:10,351 INFO: Connecting to IMAP server imap.hostinger.com:993 for account varshith@beakonagency.com [in D:\W\email_automation\app\utils\email_utils.py:414]
2025-03-11 20:48:10,909 INFO: Attempting login with username: varshith@beakonagency.com [in D:\W\email_automation\app\utils\email_utils.py:424]
2025-03-11 20:48:11,113 INFO: Successfully logged into IMAP server for varshith@beakonagency.com [in D:\W\email_automation\app\utils\email_utils.py:433]
2025-03-11 20:48:11,254 INFO: Selected INBOX with 1 messages [in D:\W\email_automation\app\utils\email_utils.py:446]
2025-03-11 20:48:11,534 ERROR: Error checking for replies: type object 'datetime.datetime' has no attribute 'datetime' [in D:\W\email_automation\app\utils\email_utils.py:621]
2025-03-11 20:48:11,535 ERROR: Traceback (most recent call last):
  File "D:\W\email_automation\app\utils\email_utils.py", line 449, in check_for_replies
    date = (datetime.datetime.now() - datetime.timedelta(days=30)).strftime("%d-%b-%Y")
AttributeError: type object 'datetime.datetime' has no attribute 'datetime'
 [in D:\W\email_automation\app\utils\email_utils.py:622]
2025-03-11 20:48:11,536 INFO: Checking replies for account: ridhit@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,537 ERROR: Error checking replies for account 3: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,537 INFO: Checking replies for account: alex@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,538 ERROR: Error checking replies for account 4: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,538 INFO: Checking replies for account: ethan@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,539 ERROR: Error checking replies for account 5: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,539 INFO: Checking replies for account: nova@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,539 ERROR: Error checking replies for account 6: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,540 INFO: Checking replies for account: growth@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,540 ERROR: Error checking replies for account 7: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,541 INFO: Checking replies for account: opportunities@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,541 ERROR: Error checking replies for account 8: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,541 INFO: Checking replies for account: connect@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,542 ERROR: Error checking replies for account 9: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,542 INFO: Checking replies for account: james@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,543 ERROR: Error checking replies for account 10: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,543 INFO: Checking replies for account: michael@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,544 ERROR: Error checking replies for account 11: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,544 INFO: Checking replies for account: sarah@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,545 ERROR: Error checking replies for account 12: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,546 INFO: Checking replies for account: david@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,546 ERROR: Error checking replies for account 13: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,546 INFO: Checking replies for account: emily@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,546 ERROR: Error checking replies for account 14: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,547 INFO: Checking replies for account: atlas@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,547 ERROR: Error checking replies for account 15: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,548 INFO: Checking replies for account: zion@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,549 ERROR: Error checking replies for account 16: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,549 INFO: Checking replies for account: upgrade@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,549 ERROR: Error checking replies for account 18: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,550 INFO: Checking replies for account: websites@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,550 ERROR: Error checking replies for account 19: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:48:11,551 INFO: Checking replies for account: fixyourwebsite@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:48:11,551 ERROR: Error checking replies for account 20: unsupported operand type(s) for +=: 'int' and 'list' [in D:\W\email_automation\app\utils\scheduler_utils.py:70]
2025-03-11 20:49:09,031 INFO: Starting check for email replies across all accounts [in D:\W\email_automation\app\utils\scheduler_utils.py:52]
2025-03-11 20:49:09,033 INFO: Checking 19 accounts for email replies [in D:\W\email_automation\app\utils\scheduler_utils.py:59]
2025-03-11 20:49:09,040 INFO: Checking replies for account: business@beakonagency.com [in D:\W\email_automation\app\utils\scheduler_utils.py:64]
2025-03-11 20:49:10,136 INFO: Selected INBOX with 24 messages [in D:\W\email_automation\app\utils\email_utils.py:446]
